### ISSUE TITLE
Plan but do not Execute - MoveIt2

### ISSUE THREAD

**Issue by ggiulian** [ggiulian/Roboerto_moveit2#1]
Here I report the bug https://github.com/ros-planning/moveit2/issues/677 where Moveit2 plans the trajectory, but does not execute it.
The discussion continues here.

**Comment by JafarAbdi** [comment]
You're missing the command & state interfaces from your `roboerto_ros_controllers.yaml` file

```yaml
roboerto_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
```
